# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER+CTRL,r,reload_config

# menu and terminal
bind=SUPER,space,spawn,rofi -show drun
bind=SUPER,Return,spawn,flatpak run org.wezfurlong.wezterm

# exit
bind=SUPER+CTRL,q,quit
bind=SUPER,w,killclient,

# switch window focus
bind=ALT,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

# swap window
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=SUPER,Tab,toggleoverview,
bind=ALT,t,togglefloating, #Put back to floating
bind=SUPER,f,togglemaximizescreen,
bind=Super,a,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,o,toggleoverlay,
bind=ALT,z,toggle_scratchpad

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# switch layout, check config file for list
bind=SUPER,n,switch_layout

# tag switch
bind=SUPER,Left,viewtoleft,0
bind=CTRL,Left,viewtoleft_have_client,0
bind=SUPER,Right,viewtoright,0
bind=CTRL,Right,viewtoright_have_client,0
bind=ALT+SUPER,Left,tagtoleft,0
bind=ALT+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tagsilent,1,0
bind=SUPER+SHIFT,2,tagsilent,2,0
bind=SUPER+SHIFT,3,tagsilent,3,0
bind=SUPER+SHIFT,4,tagsilent,4,0
bind=SUPER+SHIFT,5,tagsilent,5,0
bind=SUPER+SHIFT,6,tagsilent,6,0
bind=SUPER+SHIFT,7,tagsilent,7,0
bind=SUPER+SHIFT,8,tagsilent,8,0
bind=SUPER+SHIFT,9,tagsilent,9,0

# monitor switch
bind=alt+shift,h,focusmon,left
bind=alt+shift,l,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
bind=CTRL+SHIFT,Up,movewin,+0,-50
bind=CTRL+SHIFT,Down,movewin,+0,+50
bind=CTRL+SHIFT,Left,movewin,-50,+0
bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=CTRL+SUPER,Up,resizewin,+0,-50
bind=CTRL+SUPER,Down,resizewin,+0,+50
bind=CTRL+SUPER,Left,resizewin,-50,+0
bind=CTRL+SUPER,Right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

bind=SUPER,p,spawn_shell,grim -g "$(slurp)" - | satty -f - --copy-command wl-copy -o ~/Pictures/Screenshots/%Y%m%d_%H%M%S.png
