#Relead Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded config"

# Prefix remap
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Toggle status bar
unbind t
bind t run-shell "tmux setw -g status \$(tmux show -g -w status | grep -q off && echo on || echo off)"

# Pane splitting (keep cwd)
bind | split-window -h -c "#{?@nvim_file_dir,#{@nvim_file_dir},#{pane_current_path}}"
bind - split-window -v -c "#{?@nvim_file_dir,#{@nvim_file_dir},#{pane_current_path}}"

# Pane navigation (arrows)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Pane navigation (vim)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Zoom alt+z
bind -n M-z resize-pane -Z

bind w kill-pane
bind W kill-window

# Scroll with mouse
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" \
  "send-keys -M" \
  "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"


# Mouse support
set -g mouse on

# Prevent automatic window renaming
set -g allow-rename off

# Window numbering
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
